import type { DiscordEmbed, DiscordInteraction, Env, Explanation } from "./types";
const MAX_TERM_LENGTH = 200; const DISCORD_API = "https://discord.com/api/v10";
function decodeBase64(value: string): ArrayBuffer { const binary = atob(value); const bytes = new Uint8Array(binary.length); for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i); return bytes.buffer; }
export async function verifySignature(request: Request, publicKey: string): Promise<boolean> {
  const signature = request.headers.get("X-Signature-Ed25519"); const timestamp = request.headers.get("X-Signature-Timestamp"); if (!signature || !timestamp) return false;
  try { const key = await crypto.subtle.importKey("raw", decodeBase64(publicKey), { name: "Ed25519" }, false, ["verify"]); const prefix = new TextEncoder().encode(timestamp); const body = new Uint8Array(await request.clone().arrayBuffer()); const message = new Uint8Array(prefix.length + body.length); message.set(prefix); message.set(body, prefix.length); return await crypto.subtle.verify("Ed25519", key, decodeBase64(signature), message); } catch { return false; }
}
export function getTerm(interaction: DiscordInteraction): string | null { const raw = interaction.data?.options?.find((option) => option.name === "term")?.value; if (typeof raw !== "string") return null; const term = raw.trim(); return term && term.length <= MAX_TERM_LENGTH ? term : null; }
export function createEmbed(term: string, explanation: Explanation): DiscordEmbed { const trim = (text: string, max: number) => text.length > max ? `${text.slice(0, max - 1)}…` : text; const fields = [{ name: "意味", value: trim(explanation.meaning, 1024), inline: false as const }, { name: "ニュアンス", value: trim(explanation.nuance, 1024), inline: false as const }, { name: "例", value: trim(explanation.example, 1024), inline: false as const }]; if (explanation.warning) fields.push({ name: "注意", value: trim(explanation.warning, 1024), inline: false as const }); return { title: trim(term, 256), fields }; }
export async function sendFollowUp(interaction: DiscordInteraction, env: Env, payload: unknown, fetcher: typeof fetch = fetch) { return fetcher(`${DISCORD_API}/webhooks/${env.DISCORD_APPLICATION_ID}/${interaction.token}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
