import { verifyAsync } from "@noble/ed25519";
import type { DiscordEmbed, DiscordInteraction, Env, Explanation } from "./types";
const MAX_TERM_LENGTH = 200; const DISCORD_API = "https://discord.com/api/v10";
function decodeHex(value: string): Uint8Array { if (!/^[0-9a-f]+$/i.test(value) || value.length % 2 !== 0) throw new Error("Invalid hex"); const bytes = new Uint8Array(value.length / 2); for (let i = 0; i < bytes.length; i++) bytes[i] = Number.parseInt(value.slice(i * 2, i * 2 + 2), 16); return bytes; }
export async function verifySignature(request: Request, publicKey: string): Promise<boolean> {
  const signature = request.headers.get("X-Signature-Ed25519"); const timestamp = request.headers.get("X-Signature-Timestamp"); if (!signature || !timestamp) return false;
  try { const prefix = new TextEncoder().encode(timestamp); const body = new Uint8Array(await request.clone().arrayBuffer()); const message = new Uint8Array(prefix.length + body.length); message.set(prefix); message.set(body, prefix.length); return await verifyAsync(decodeHex(signature), message, decodeHex(publicKey)); } catch { return false; }
}
export function getTerm(interaction: DiscordInteraction): string | null { const raw = interaction.data?.options?.find((option) => option.name === "term")?.value; if (typeof raw !== "string") return null; const term = raw.trim(); return term && term.length <= MAX_TERM_LENGTH ? term : null; }
export function createEmbed(term: string, explanation: Explanation): DiscordEmbed { const trim = (text: string, max: number) => text.length > max ? `${text.slice(0, max - 1)}…` : text; const fields = [{ name: "意味", value: trim(explanation.meaning, 1024), inline: false as const }, { name: "ニュアンス", value: trim(explanation.nuance, 1024), inline: false as const }, { name: "例", value: trim(explanation.example, 1024), inline: false as const }]; if (explanation.warning) fields.push({ name: "注意", value: trim(explanation.warning, 1024), inline: false as const }); return { title: trim(term, 256), fields }; }
export async function sendFollowUp(interaction: DiscordInteraction, env: Env, payload: unknown, fetcher: typeof fetch = fetch) { return fetcher(`${DISCORD_API}/webhooks/${env.DISCORD_APPLICATION_ID}/${interaction.token}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); }
